# Generated by Django 4.0.4 on 2022-05-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_mark_type_product_material_product_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='schedule',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
